/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/cQZTcNGDz7J
 */
import Image from "next/image";

export function ImageGallery() {
  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4 w-full max-w-7xl mx-auto p-4">
      <h2 className="col-span-full text-3xl font-bold mb-6 text-center">Our Work</h2>
      <div className="relative overflow-hidden rounded-lg">
        <Image
          alt="Project 1"
          className="aspect-square object-cover w-full"
          height="600"
          src="/placeholder.svg"
          width="600"
        />
        <p className="mt-2 text-center">Project 1 Description</p>
      </div>
      <div className="relative overflow-hidden rounded-lg">
        <Image
          alt="Project 2"
          className="aspect-square object-cover w-full"
          height="600"
          src="/placeholder.svg"
          width="600"
        />
        <p className="mt-2 text-center">Project 2 Description</p>
      </div>
      <div className="relative overflow-hidden rounded-lg">
        <Image
          alt="Project 3"
          className="aspect-square object-cover w-full"
          height="600"
          src="/placeholder.svg"
          width="600"
        />
        <p className="mt-2 text-center">Project 3 Description</p>
      </div>
      <div className="relative overflow-hidden rounded-lg">
        <Image
          alt="Project 4"
          className="aspect-square object-cover w-full"
          height="600"
          src="/placeholder.svg"
          width="600"
        />
        <p className="mt-2 text-center">Project 4 Description</p>
      </div>
    </div>
  );
}
