/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/zy9CCqYQyMU
 */
import { Button } from "@/components/ui/button";
import Link from "next/link";

export function PageNotFound() {
  return (
    <>
      <main className="h-screen bg-gray-100 flex flex-col items-center justify-center text-center px-4 sm:px-6 lg:px-8">
        <h1 className="text-6xl font-bold text-gray-900">404</h1>
        <p className="mt-2 text-lg text-gray-600">
          {`Oops! The page you're looking for does not exist.`}
        </p>
        <p className="mt-2 text-gray-500">
          {`It seems you've found something that used to exist, or you spelled something wrong. Don't
          worry, we'll get you back on track.`}
        </p>

        <Link href={"/"}>
          <Button className="mt-6" variant="secondary" >
            Return Home
          </Button>
        </Link>
      </main>
    </>
  );
}
